source 'https://rubygems.org'

gem 'capybara', '3.35.3'
gem 'cucumber', '3.1.2'
gem 'faker'
gem 'ffaker'
gem 'json'
gem 'poltergeist'
gem 'pry', '0.11.3'
gem 'report_builder', '1.9'
gem 'reportportal', '0.7'
gem 'rspec', '3.6.0'
gem 'rubytree', '1.0.0'
gem 'screen-recorder'
gem 'selenium-webdriver', '3.142.7'